-----------------------------------
-- ps2_2007: keep shop lists to items the 2007 PS2 client has (generated by research/tools/lsb_textids_2007.py;
-- report 24). An item the client does not know shows as an empty, unbuyable line; buying it would still take gil.
-- Undo: remove the 'ps2_2007' line from modules/init.txt and restart the server.
-----------------------------------
require('modules/module_utils')
local known = require('modules/ps2_2007/item_ids_2007')
-----------------------------------
local m = Module:new('ps2_2007_shop_items')

local function filter(stock)
    local out = {}
    for _, stockItem in ipairs(stock) do
        if known[stockItem[1]] then
            table.insert(out, stockItem)
        end
    end

    return out
end

m:addOverride('xi.shop.general', function(player, stock, log)
    return super(player, filter(stock), log)
end)

m:addOverride('xi.shop.generalGuild', function(player, stock, guildSkillId)
    return super(player, filter(stock), guildSkillId)
end)

m:addOverride('xi.shop.curioVendorMoogle', function(player, stock)
    return super(player, filter(stock))
end)
