-- generated by work/b15_hidden/tools/gen_debug_npcs.py (report 32)
-- [LSB zone script folder] = { [LSB npc script name] = { cutscene ids from the 2012 client event DAT } }
return {
    ['Hall_of_Transference'] = {
        ['FXTEST'] = { 50 },
    },
    ['Abyssea-Konschtat'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
    },
    ['Abyssea-Tahrongi'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
    },
    ['Al_Zahbi'] = {
        ['Saraware_test'] = { 99 },
    },
    ['Chocobo_Circuit'] = {
        ['Mes-Test'] = { 999 },
    },
    ['Southern_San_dOria_[S]'] = {
        ['test_TGS_npc'] = { 101 },
        ['OPS-Debug'] = { 303 },
        ['test3'] = { 23, 24, 43, 47, 59 },
        ['test4'] = { 23, 24, 44, 47 },
    },
    ['Jugner_Forest_[S]'] = {
        ['testA'] = { 200, 201, 202, 203 },
        ['testB'] = { 200, 201, 202, 203 },
        ['testC'] = { 200, 201, 202, 203 },
    },
    ['Bastok_Markets_[S]'] = {
        ['test_guest'] = { 600 },
        ['OPS-Debug'] = { 303 },
    },
    ['Rolanberry_Fields_[S]'] = {
        ['test_hume01'] = { 100 },
    },
    ['Windurst_Waters_[S]'] = {
        ['OPS-Debug'] = { 303 },
    },
    ['West_Sarutabaruta_[S]'] = {
        ['DummyLehko'] = { 108 },
    },
    ['Sauromugue_Champaign_[S]'] = {
        ['test_orc01'] = { 100 },
        ['test_orc02'] = { 100 },
        ['test_orc03'] = { 100 },
        ['test_dog01'] = { 100 },
    },
    ['East_Ronfaure'] = {
        ['Debug'] = { 7013 },
    },
    ['La_Theine_Plateau'] = {
        ['Debug'] = { 7013 },
    },
    ['Batallia_Downs'] = {
        ['TEST_Dungeon_Debug'] = { 5507 },
        ['Debug'] = { 7013 },
    },
    ['North_Gustaberg'] = {
        ['DEBUG_ACTOR'] = { 99 },
    },
    ['South_Gustaberg'] = {
        ['Debug'] = { 7013 },
    },
    ['Konschtat_Highlands'] = {
        ['Debug'] = { 7013 },
    },
    ['Rolanberry_Fields'] = {
        ['Debug'] = { 7013 },
    },
    ['East_Sarutabaruta'] = {
        ['Debug'] = { 7013 },
    },
    ['Tahrongi_Canyon'] = {
        ['Debug'] = { 7013 },
    },
    ['Sauromugue_Champaign'] = {
        ['TEST_Dungeon_Debug'] = { 5507 },
        ['Debug'] = { 7013 },
    },
    ['The_Sanctuary_of_ZiTah'] = {
        ['ScenarioBoss'] = { 202 },
    },
    ['Abyssea-La_Theine'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
    },
    ['Ghelsba_Outpost'] = {
        ['kagami_test'] = { 32000, 32004 },
    },
    ['Throne_Room_[S]'] = {
        ['fire_test'] = { 11 },
    },
    ['Walk_of_Echoes'] = {
        ['test_PT01'] = { 100 },
        ['test_PT02'] = { 100 },
        ['SUNACHI_TEST1'] = { 111 },
        ['Ldummy'] = { 4 },
    },
    ['GM_Home'] = {
        ['Fame'] = { 21 },
        ['San_dOria'] = { 12 },
        ['Bastok'] = { 13 },
        ['Windurst'] = { 14 },
        ['Key_Item'] = { 20 },
        ['Conquest_Debug'] = { 22 },
        ['Herald'] = { 26 },
        ['Ballista_Item'] = { 27 },
        ['Blenner_itembox'] = { 50 },
        ['pvp2_itembox_debug'] = { 51 },
        ['Juno_item'] = { 24 },
        ['Ex_Scenario'] = { 30 },
        ['Party_test'] = { 25 },
        ['testkun0'] = { 31 },
        ['Equip_Navi'] = { 40 },
        ['ship'] = { 41 },
        ['Mannequin'] = { 42 },
        ['Promathia'] = { 44 },
        ['Promathia_BattleField'] = { 45 },
        ['Fellow'] = { 46 },
        ['Fish_selecter'] = { 47 },
        ['Bigfish_Maker'] = { 49 },
        ['Ahturhgan'] = { 65 },
        ['Assault'] = { 66 },
        ['Programmer'] = { 70 },
        ['Localize'] = { 72, 76, 77, 79 },
        ['Lottery-Maker'] = { 75 },
        ['Altana'] = { 73 },
        ['Abyssea'] = { 0 },
        ['Mogsack_Moogle'] = { 1 },
        ['TABULA_MAKER'] = { 80 },
        ['Bonanza_Master'] = { 81 },
        ['5thTrumpet'] = { 82 },
        ['RandomItemMaker'] = { 83 },
        ['Dealer_Moogle'] = { 84, 85 },
        ['RandomItemDebugger'] = { 86 },
        ['6thTrumpet'] = { 87 },
        ['7thTrumpet'] = { 88 },
        ['Evorith_Maker'] = { 90 },
        ['Level-Check'] = { 119 },
        ['Porter_Moogle'] = { 92, 93, 94, 95, 97 },
        ['Magian_MoogleHood'] = { 96 },
        ['Atmacite_Refiner'] = { 2 },
        ['Voidwatch_Officer'] = { 3, 5, 6, 7, 8, 9, 10, 11, 15 },
        ['Poet'] = { 121 },
        ['Volunteer'] = { 122 },
        ['Changeable'] = { 123, 124 },
        ['Judge'] = { 125 },
        ['Item_give'] = { 128 },
        ['Lea_lover'] = { 129, 130 },
        ['Girl'] = { 131, 132 },
        ['Boy'] = { 133, 134 },
        ['Fat'] = { 135, 136 },
        ['Unstable'] = { 137 },
        ['Yajiuma'] = { 139 },
        ['Map-Change'] = { 16 },
    },
    ['Abyssea-Attohwa'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
        ['BCG_Debug_Master'] = { 122 },
    },
    ['Abyssea-Misareaux'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
        ['BCG_Debug_Master'] = { 122 },
    },
    ['Abyssea-Vunkerl'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
        ['BCG_Debug_Master'] = { 122 },
    },
    ['Abyssea-Altepa'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
        ['Debug_Koryakudo_NPC'] = { 121 },
    },
    ['Northern_San_dOria'] = {
        ['mgtest'] = { 862, 863 },
    },
    ['Bastok_Mines'] = {
        ['mgtest'] = { 585, 586 },
    },
    ['Port_Windurst'] = {
        ['mgtest'] = { 854, 855 },
    },
    ['Upper_Jeuno'] = {
        ['kagami_test'] = { 10043, 10044, 10046, 10064, 10072, 10073, 10074, 10075 },
    },
    ['Selbina'] = {
        ['mgtest'] = { 1135, 1136 },
    },
    ['Mhaura'] = {
        ['mgtest'] = { 334, 335 },
    },
    ['Abyssea-Uleguerand'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
        ['Debug_Koryakudo_NPC'] = { 121 },
    },
    ['Abyssea-Grauberg'] = {
        ['Time_Master_Debug'] = { 2000 },
        ['AP_Master_Debug'] = { 2181 },
        ['Debug_Koryakudo_NPC'] = { 121 },
    },
}
