-----------------------------------
-- lan_gmhome: the developers' debug NPCs (GM Home zone 210, plus =TEST=/Debug/test NPCs in 40 other zones) play the
-- debug cutscenes/menus that are still in the 2012 client data (report 32). Cutscene ids come from the 2012 event DATs
-- (lan_gmhome_data.lua, generated by work/b15_hidden/tools/gen_debug_npcs.py). Every choice a menu returns is printed
-- to the GM and to the server log; nothing is granted or changed. NPCs that already have an LSB script are untouched.
-- The 2012 client numbers many NPCs differently from LSB; the proxy's 2012 NPC map (PS2PROXY_NPC_MAP=
-- work/b13_2012/native/lsb_ids_2012/npc_id_map.json) translates them. Some of these NPCs are hidden in LSB: use
-- !npchere <id> (ids in work/b15_hidden/out/debug_npcs.tsv) to bring one to you.
-----------------------------------
require('modules/module_utils')
local cfg  = require('modules/lan_hidden/lua/lan_hidden_config')
local data = require('modules/lan_hidden/lua/lan_gmhome_data')
-----------------------------------
local m = Module:new('lan_gmhome', cfg.GMHOME_DEBUG_NPCS == true)

local function say(player, npcName, text)
    print(string.format('[lan_gmhome] %s / %s: %s', player:getName(), npcName, text))
    player:printToPlayer(text, xi.msg.channel.SYSTEM_3, npcName)
end

local function makeNpc(script, csids)
    local npcTable = {}

    npcTable.onTrigger = function(player, npc)
        -- several cutscenes: step through them on each talk
        local key = 'lanDbg_' .. script
        local idx = (player:getLocalVar(key) % #csids) + 1
        player:setLocalVar(key, idx)
        say(player, script, string.format('starting debug cutscene %d (%d of %d)', csids[idx], idx, #csids))
        player:startEvent(csids[idx])
    end

    npcTable.onEventUpdate = function(player, csid, option, npc)
        say(player, script, string.format('event %d update: option %d (0x%X)', csid, option, option))
    end

    npcTable.onEventFinish = function(player, csid, option, npc)
        say(player, script, string.format('event %d finished: option %d (0x%X)', csid, option, option))
    end

    return npcTable
end

local function wire()
    local n = 0
    for folder, npcs in pairs(data) do
        xi.zones[folder]      = xi.zones[folder] or {}
        xi.zones[folder].npcs = xi.zones[folder].npcs or {}
        for script, csids in pairs(npcs) do
            if #csids > 0 and xi.zones[folder].npcs[script] == nil then
                xi.zones[folder].npcs[script] = makeNpc(script, csids)
                n = n + 1
            end
        end
    end

    print(string.format('[lan_gmhome] %d debug NPCs wired to their 2012 cutscenes', n))
end

m:addOverride('xi.server.onServerStart', function()
    wire()
    super()
end)
