.section .rodata
.balign 16
.global irx_iomanX
irx_iomanX:
.incbin "irx/iomanX.irx"
.global irx_iomanX_end
irx_iomanX_end:
.balign 16
.global irx_fileXio
irx_fileXio:
.incbin "irx/fileXio.irx"
.global irx_fileXio_end
irx_fileXio_end:
.balign 16
.global irx_ps2dev9
irx_ps2dev9:
.incbin "irx/ps2dev9.irx"
.global irx_ps2dev9_end
irx_ps2dev9_end:
.balign 16
.global irx_ps2atad
irx_ps2atad:
.incbin "irx/ps2atad.irx"
.global irx_ps2atad_end
irx_ps2atad_end:
.balign 16
.global irx_ps2hdd
irx_ps2hdd:
.incbin "irx/ps2hdd.irx"
.global irx_ps2hdd_end
irx_ps2hdd_end:
.balign 16
.global irx_ps2fs
irx_ps2fs:
.incbin "irx/ps2fs.irx"
.global irx_ps2fs_end
irx_ps2fs_end:
.balign 16
.global irx_fakesound
irx_fakesound:
.incbin "irx/fakesound.irx"
.global irx_fakesound_end
irx_fakesound_end:
.balign 16
