-- generated by legacy/tools/build_beta_music.py: beta track -> installed track id
return {
    { beta = 101, id = 901, label = 'beta take of track 101 (retail: Altaieu battle solo, Attohwa Chasm battle solo, Batallia Downs S battle solo)' },
    { beta = 102, id = 902, label = 'beta take of track 102 (retail: Altar Room battle party, Beadeaux battle party, Bostaunieux Oubliette battle party)' },
    { beta = 103, id = 903, label = 'beta take of track 103 (retail: Batallia Downs battle party, Beaucedine Glacier battle party, Behemoths Dominion battle party)' },
    { beta = 104, id = 904, label = 'beta take of track 104' },
    { beta = 105, id = 905, label = 'beta take of track 105 (retail: Mhaura battle party, Mhaura battle solo, Mhaura day)' },
    { beta = 106, id = 906, label = 'beta take of track 106 (retail: Ship Bound For Mhaura Pirates day, Ship Bound For Mhaura Pirates night, Ship Bound For Mhaura day)' },
    { beta = 107, id = 907, label = 'beta take of track 107 (retail: Northern San Doria battle party, Northern San Doria battle solo, Northern San Doria day)' },
    { beta = 108, id = 908, label = 'beta take of track 108' },
    { beta = 109, id = 909, label = 'beta take of track 109 (retail: East Ronfaure day, East Ronfaure night, West Ronfaure day)' },
    { beta = 111, id = 911, label = 'beta take of track 111' },
    { beta = 151, id = 951, label = 'beta take of track 151 (retail: Heavens Tower battle party, Heavens Tower battle solo, Port Windurst battle party)' },
    { beta = 152, id = 952, label = 'beta take of track 152 (retail: Bastok Markets battle party, Bastok Markets battle solo, Bastok Markets day)' },
    { beta = 153, id = 953, label = 'beta take of track 153' },
}
